birobirobiro/awesome-shadcn-ui

- README.md
I added v0.dev, which is one of the best tools out there that is based on shadcn/ui. You can generate UI through text and image prompts. It provides React and HTML code, where you can either copy-and-paste it or integrate it via their provided CLI tool.
> Added v0.dev

- README.md
Adds https://github.com/sujjeee/nextjs-dnd link
> adds new dnd lib

- README.md
Updating the storybook link to the one indicated on [storybook-shadcn](https://github.com/JheanAntunes/storybook-shadcn) project
> doc - update storybook project link

- README.md
love this project! just added some contributions for animated components
> Update README.md with magicui

- README.md
This pull request adds the Planner component, a highly adaptable scheduling component tailored for React applications. The Planner component can be used to create and manage schedules, appointments, and tasks in a flexible and customizable way. It provides a range of features and options to suit different use cases and can be easily integrated into existing React projects.
> Add Planner component for React applications

- README.md
Rewrite the description of shadcn-ui-sidebar.
> update: change shadcn-ui-sidebar description

- README.md
This pull request adds the Capture-Photo component, a versatile, browser-based React component designed to streamline the integration of camera functionalities directly into web applications.
> Add Capture-Photo component for browser-based camera functionalities

- README.md
The Search-Address component is being added to provide a flexible and interactive search interface for addresses. It utilizes the Nominatim service from OpenStreetMap for powerful address search capabilities. This component will enhance the functionality of the application by allowing users to easily search for addresses and retrieve relevant information.
> Add Search-Address component for interactive address search

- README.md
added a new platform to watch anime, kdrama, movie, and tv-shows created using shadcn/ui
> Added new platform

- README.md
the most starred and inspiration of other vscode extensions listed already
https://x.com/selemondev/status/1735992269486882867
> update: new extension 

- README.md
I was about to add two new tools but realized they were in too late since it wasn't organized. It's better sorted imo, making it easier to find specific repos.
> Sorted the bullets of the README.md

- README.md
Adding farmui.com as good resource for shadcn and tailwind css based UIs
> feat: adding farmui.com

- README.md
**Description:**
I am proposing the addition of `turborepo-launchpad` to the Projects and Boilerplates section of the `awesome-shadcn-ui` list. This repository represents a robust monorepo setup utilizing Turbo to streamline the development environment and build processes for projects using shadcn. It provides a well-documented, ready-to-use boilerplate that helps developers kick-start their own shadcn projects with the best practices in scalability and maintenance.
**Key Features:**
- **Monorepo Setup:** Centralizes multiple packages and apps, making it easier to manage dependencies and shared assets.
- **Turbo Integration:** Leverages Turbo for efficient task orchestration, significantly speeding up builds and tests.
- **Extensive Documentation:** Includes detailed instructions and …
> Add 'turborepo-launchpad' to Project and Boilerplates section

- README.md
Added Shadcn/ui blocks URL: https://shadcn-ui-blocks.vercel.app/ to the library
> Added one link under Libs and Components

- README.md
---
name: feat: Add shadcn-timeline
about: this is a timeline component, i think it will be very useful, when the official component of shadcn has not been made yet.
---
Customizable and re-usable timeline component for you to use in your projects. Built on top of shadcn.
> feat: Add shadcn-timeline

- README.md
---
name: feat: Add minimal-tiptap editor component
about: Minimal tiptap editor for shadcn
---
**What is it?**  Minimal setup editor for shadcn using tiptap
**What category does it belong to?** (Libs and Components)
**Anything else? (opt
ional)** 
> feat: Add minimal-tiptap Component

- README.md
> link: component-library-link

- README.md
Added extra commit for removing extra space
---
name: feat: Add confirm-dialog component
about: Global wrapper for using alert-dialog from shadcn
---
> feat: Add confirm-dialog

- README.md
---
name: feat: supabase + nextjs authentication starter template
about: Add a new awesome thing related to nextjs, supabase and shadcn-ui
labels: boilerplate/template
---
A starter template for NextJS which uses Supabase as the backend service for authentication.
Boilerplates/Templates
**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed …
> feat: Add Aupabase NextJS starter template

- README.md
---
name: Add Lukacho UI Components library
https://ui.lukacho.com/
> feat: Add Lukacho UI Components library

- README.md
---
name: feat: Add shadcn-calendar-heatmap component
---
**What is it?** It is a modern alternative to primitive react heatmaps. The component exposes a simple set of input props, allowing you to annotate your calendar with themes and showcase meaningful content to users. Example use case could be to show user progress, reservation booking status, and so much more. 
**Anything else? (optional)** (e.g. screenshots, additional information, etc.) N/A
- [ x] I checked that it is in alphabetical order.
- [ x] I have checked that the awesome thing is not already listed.
- [ x] I have provided a clear and concise description of the awesome thing.
- [ x] I have provided a …
> add: shadcn-calendar-heatmap

- README.md
---
name: feat: Add mixcnui
---
**What is it?** Mixui is a collection of animated or re-usable component for currently for Nextjs.
- [x ] I checked that it is in alphabetical order.
- [ x] I have checked that the awesome thing is not already listed.
- [ x] I have provided a clear and concise description of the awesome thing.
- [ x] I have provided a link to the awesome thing.
- [ x] I have assigned the correct category to the awesome thing.
> add: mixcnui

- README.md
---
name: feat: Add Stocks, charts using shadcn/ui
about: Add stock Picker using Next.js, React Server Components, and shadcn/ui charts
https://stocks-blue-rho.vercel.app/
---
> feat: Add Stocks, charts using shadcn/ui

- README.md
---
name: feat: Add Shadcn Address Autocomplete (Google Places API)
about: An address autocomplete component built with Google Places API and shadcn components.
https://github.com/NiazMorshed2007/shadcn-address-autocomplete/assets/77217706/cfd645c5-b8a9-46cf-bbb1-dc83d86fe142
---
**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the …
> feat: Add Shadcn Address Autocomplete (Google Places API)

- README.md
---
name: feat: Add Fancy Switch Component
about: Add a new fancy switch component
---
**What category does it belong to?** (Libs and Components)
**Anything else?**
> feat: add fancy switch component

- README.md
---
name: feat: add "Grade Calculator" to the list
about: This PR will add the project "Grade Calculator" to the curated list
---
This grade calculator is an open source project built using shadcn/ui and NextJS. It is a progressive web app, aiming to provide students with a better overview on their academic performance.
Some key features:
- Customizable numeric grade scale
- Visualizing your grades using graphs and charts
- View the grades you need to pass a subject at a glance
- Supports grade weights
- See the subjects you struggle in summarized
- Cloud synced for easy access anywhere
- [Legacy version](https://legacy.grades.nstr.dev/) available for usage without account and cloud (unmaintained)
**What category does it belong to?** Plattform/App …
> feat: add "Grade Calculator" to the list

- README.md
---
name: feat: Add shadcn-carousel-testimonials
---
> feat: Add shadcn-carousel-testimonials

- README.md
---
name: feat: add crypto-charts
about: Add a new awesome charts for shadcn/ui
https://crypto-charts-pi.vercel.app/?ticker=BTC/USD
---
> feat: add crypto-charts

- README.md
> Shadcn Datetime Picker

- README.md
---
JobSync App built with nextjs, shadcn, prisma, sqlite, langchain
---
JobSync is a job seekers' assistant to manage job search efficiently, its is a web app companion for managing your job search journey. This free and open-source project is designed to help job seekers efficiently track and organize their job applications. 
Apps
**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of …
> Jobsync app

- README.md
---
---
MemFree - Open Source Hybrid AI Search Engine, Instantly Get Accurate Answers from the Internet, Bookmarks, Notes, and Docs. Support One-Click Deployment.
Tools
- Hybrid AI Search Engine
- One-Click Chrome Bookmarks Sync and Index
- Support multiple traditional search engines as source
- Self-hosted Super Fast Serverless Vector Database
- Self-hosted Super Fast Local Embedding and Rerank Service
- Full Code Open Source
- One-Click Deployment On Production
**Please note:** If …
> Add Memfree to tools

- README.md
---
name: feat: Add ReactSelect with ShadCN Styling
---
An implementation of the very popular [React-Select](https://react-select.com/home#getting-started) library, formatted for ShadCN. ShadCN's select component has problems and this solution is a good alternative
**Important:** The idea of this repository is to bring together free projects for …
> Add React-Select library

- README.md
---
name: feat: Add shadcn-date-picker
about: Advanced date picker with range selection, year and month selection, and more.
---
I created an advanced version of shadcn date picker.
This version enables the user to navigate through years.
This is especially useful when selecting birth dates.
Components
For now it only includes this feature, but I am planning on adding more in the future. …
> feat: :sparkles: add shadcn-date-picker

- README.md
---
name: feat: add opendocs
about: Beautifully designed template that you can use for your projects for free. Accessible. Customizable. Open Source with i18n support.
---
A beautifully designed template that you can use for your projects for free. Accessible. Customizable. Open Source with i18n support built on top of shadcn/ui site and components.
**What category does it belong to?** (Boilerplates/Templates)
**Important:** The idea of this repository is to bring together free projects for open-source …
> docs(boilerplate): add opendocs

- README.md
---
---
Integration of various popular payment gateways, such as Stripe, Razorpay, PayPal, and Coinbase, into a Next.js 14 application. This showcases how to implement these payment solutions within a modern web framework.
**Important:** The idea of this repository is to bring together free …
> add: payment gateways integrate demo

- README.md
---
name: [shadcn theme editor](https://github.com/programming-with-ia/shadcn-theme-editor/)
about: Manage Shadcn theme colors with an intuitive UI.
labels: Colors and Customizations
---
Shadcn Theme Editor is a user-friendly component designed to simplify the process of managing and customizing theme colors in Shadcn-based projects. This package provides an intuitive UI with buttons for different color properties, allowing developers to easily adjust and preview theme colors in real-time. Although the package is optimized for ease of use, its build size is substantial, so it is recommended to install it as a development dependency. This tool empowers developers to create consistent, visually appealing themes without diving into complex CSS, making it an essential addition to your Shadcn …
> Add `shadcn-theme-editor`

- README.md
---
---
memergez is a website where you can generate memes in seconds. just enter a text/avatar url and generate
Website
check readme in [github](https://github.com/avalynndev/memergez)
**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed …
> memer generator using shadcn

- README.md
---
name: feat: Add animata
about: Add a new animation components lib
---
**What is it?** Hand-crafted ✍️ interaction animations and effects from around the internet 🛜 to copy and paste into your project.
**Anything else? (optional)** https://animata.design/
> feat: add animata

- README.md
noticed u added``` [shadcn-hsl-preview]([https://github.com/dexxiez/shadcn-hsl-preview](https://marketplace.visualstudio.com/items?itemName=dexxiez.shadcn-color-preview))``` instead of this: ```[shadcn-hsl-preview](https://marketplace.visualstudio.com/items?itemName=dexxiez.shadcn-color-preview)``` so fixed that
> fixed linking and fix awesome item

- README.md
---
---
Razor component library for Blazor, inspired by the shadcn/ui components
Ports
> Add Sysinfocus simple/ui to ports

- README.md
---
name: feat: Globe Graph
about: Globe Graph is a web app that visualizes the countries data like GDP, GDP per capita, and population in different years using many charts.
---
Globe Graph is a web app that visualizes the countries data like GDP, GDP per capita, and population in different years using many charts.
Apps
- [✔️] I checked that it is in alphabetical order.
- [✔️] I have checked that the awesome thing is not already listed.
- [✔️] I have provided a clear and concise description of the awesome thing.
- [✔️] I have provided a link to the awesome thing.
- [✔️] …
> added new site for explore country data in charts

- README.md
---
name: feat: Add andresam.xyz - Portfolios/Personal Blog
---
A revamped version of the popular tailwind-nextjs-starter-blog featuring ShadCN components, along with a resume section and experience timeline component.
Portfolio / Personal Blog
[andrewsam.xyz](https://www.andrewsam.xyz/)
**Important:** The idea of this repository is to bring together …
> andresam.xyz - Portfolios/Personal Blog

- README.md
> added ShadcnUI-Templates.com

- README.md
> added bundui.io

- README.md
Add a collection of reusable animated react components, inspired by shadcn-ui.
> feat: Add UI Beats

- README.md
A component for hierarchical lists of data with nested levels that can be expanded and collapsed.
https://github.com/mrlightful/shadcn-tree-view
Category: Component
> feat: Add Tree View component

- README.md
A project template for creating a Tauri app with Vite, React, and Tailwind CSS.
https://github.com/mrlightful/create-tauri-core
Category: Template
> feat: Add Tauri template

- README.md
> Add color picker component

- README.md
A clean Next.js template with TypeScript, TailwindCSS, Shadcn/ui, and Prettier. Optimized for quick project setup with handy packages.
https://template-next-official.vercel.app/
Category: Boilerplates/Templates
>  feat: Add Template-NEXT

- README.md
This WordPress Plugin Boilerplate is made with modern web technologies and tools such as React, TypeScript, SASS, Tailwind CSS, Shadcn UI, Vite, Grunt.js, Storybook, HMR, and more.
https://github.com/prappo/wordpress-plugin-boilerplate
**Category:** Boilerplates / Templates
> feat: Add new WordPress Plugin Boilerplate

- README.md
> add motion-number

- README.md
---
name: feat: Add [`shadcn-zod-form`](https://github.com/ilyichv/shadcn-zod-form)
about: Add `shadcn-zod-form` a CLI tool to generate shadcn/ui forms from zod schemas
---
An easy to use CLI to generate shadcn forms from zod schemas.
**What category does it belong to?** - Tools
> add shadcn-zod-form

- README.md
---
name: feat: Add [shubhporwal.me](https://www.shubhporwal.me/) portfolio
---
Portfolio
Websites and Portfolios Inspirations
> add `shubhporwal.me` portfolio

- README.md
UI Builder is a React component that provides a no-code, visual way to create UIs, compatible with ShadCN and custom components.
https://github.com/olliethedev/ui-builder
category: Component
> feat: add ui-builder component

- README.md
- Added a link to ewgenius/ui, a tool for creating custom themes for shadcn/ui using vibrant palettes from Radix Colors.
- Added a link to Radix Colors, a comprehensive color system for designing beautiful, accessible websites and apps.
**What category does it belong to?** Colors and customization
> Added ewgenius/ui and radix colors

- README.md
---
name: Sharable Form Builder
about: A form builder that you can inject in your app for your users to build dynamic forms and collect data without having to write too much text.
labels: enhancement
---
- Sharable form builder
- A component for building forms using shadcnUI
- [no] I checked that it is in alphabetical order.
- [yes ] I have checked that the awesome thing is not already listed.
- [yes] I have provided a clear and concise description of the awesome thing.
- [yes] I have provided a link to the awesome thing.
- [yes] I have assigned the correct category to the awesome …
> feat: add sharable form builder

- .github/pull_request_template.md
fix yaml parsing issue in pull_request_template.md
> fix yaml parsing issue

- README.md
---
name: feat: Add Datetime Picker
about: A powerful datetime picker with support for timezones, minimum and maximum dates, and month/year selection.
---
Datetime Picker Component
Components
> feat: add datetime picker

- README.md
---
name: feat: shadcn-cookie-consent
about: Added Shadcn Cookie Consent Component and Nextjs Saas starter kit build with Shadcn UI
---
Shadcn Cookie Consent Component and Shad Shadcn base Nextjs Saas Starter Kit
Components
- [x ] I checked that it is in alphabetical order.
- [x ] I have checked that the awesome thing is not already listed.
- [x ] I have provided a clear and concise description of the awesome thing.
- [x ] I have provided a link to the awesome thing.
- [x ] I have assigned the correct category to the awesome thing.
**Please note:** If you are adding a …
> Add customizable shadcn-cookie-consent component

- README.md
---
name: feat: Add NumberFlow
about: A React component to transition, localize, and format numbers. Dependency-free. Accessible. Customizable.
labels: Libs and Components
---
> Add NumberFlow

- README.md
Inspira UI
Libs
https://inspira-ui.com/components/all
> add Inspira UI

- README.md
---
name: "feat: Add Stunning UI"
about: "Stunning UI is a collection of interactive Tailwind CSS components built for Vue and Nuxt."
labels: 
---
> Add Stunning UI

- README.md
---
name: "feat: Add Origin UI"
about: "Beautiful UI components built with Tailwind CSS and Next.js"
labels:
---
> Add Origin UI

- README.md
---
name: "feat: shadcn-next-workflows"
about: "Interactive workflow builder using React Flows, Next.js, and Shadcnui. Create, connect, and validate custom nodes easily."
labels:
- templates
- boilerplates
---
Interactive workflow builder using React Flows, Next.js, and Shadcnui. Create, connect, and validate custom nodes easily.
Boilerplates/Templates
> add: shadcn-next-workflows

- README.md
---
name: "feat: Add shadcn browser extension starter template"
about: "Browser extension starter kit featuring Plasmo, React, Shadcn, and tRPC"
labels:
- templates
- boilerplate
---
A browser extension starter kit featuring Plasmo, React, Shadcn, and tRPC
Boilerplates/Templates
**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an …
> Add shadcn browser extension starter template

- README.md
---
labels:
- feature
---
A registry that provides a set of reusable hooks that are installable via `shadcn` CLI.
**What category does it belong to?**
Libs and Components 
> add hookagain

- README.md
Syncing [plate](https://github.com/udecode/plate) description
> Edit plate description

- README.md
---
name: "feat: Add shadcn-timeline"
about: "Customisable shadcn timeline component"
labels:
---
**What is it?** A simple customisable shadcn timeline component
**Anything else? (optional)** 
> add shadcn-timeline

- README.md
---
labels:
- shadcn-editor
---
- [ x] I checked that it is in alphabetical order.
- [ x] I have checked that the awesome thing is not already listed.
- [ x] I have provided a clear and concise description of the awesome thing.
- [ x] I have provided a link to the awesome thing.
- [ x] I have assigned the correct category to the awesome thing.
**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of …
> add shadcn-editor

- README.md
---
name: "feat: Add kokonut-ui"
about: "Modern, interactive, customizable UI components"
labels:
libs & components
---
**What is it?** A collection of modern, interactive, customizable UI components built with shadcn & TailwindCSS.
**What category does it belong to?** Libs & Components
- [ ✅] I checked that it is in alphabetical order.
- [ ✅] I have checked that the awesome thing is not already listed.
- [ ✅] I have provided a clear and concise description of the awesome thing.
- [ ✅] I have provided a link to the awesome thing.
- [ ✅] I have assigned the correct category to the awesome thing.
**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of contents as …
> add kokonut ui

- README.md
---
name: "feat: Add Lauch UI"
about: "Landing page components built with React, Shadcn/ui and Tailwind that you can copy/paste into your project."
labels:
- feature
---
**What is it?** A library of landing page components built with React, Shadcn/ui and Tailwind
> Add Launch UI

- README.md
---
name: "feat: add tailwindcss-motion"
about: "A new simple syntax animation library. Batteries included. Infinitely configurable."
labels:
- Animation
---
> add tailwindcss-motion

- README.md
> add druid/ui to libs

- README.md
---
name: "feat: Add midday app"
labels:
- feature
---
**What is it?** An all-in-one tool to manage finances, track projects, store files, and send invoices.
**What category does it belong to?** Apps
**Anything else? (optional)** 
> add midday app

- README.md
---
name: " add pqoqubbw animated icons"
about: ""
labels:
- feature
---
**What is it?** beautifully crafted animated icons using `framer-motion` and `lucide`
> add pqoqubbw animated icons

- README.md
---
name: "feat: Supercharged Shadcn Components"
about: "Ready-to-use React components built on top of shadcn/ui, specializing  in building simpler, type-safe react-hook-form components."
labels:
- Simpler, type-safe react-hook-form components
- Amazing input and button with floating labels
---
Supercharged Shadcn Components is an open-source ReactJS component library designed to simplify your workflow with pre-built, reusable components built on top of shadcn/ui inspired by Material-UI and other libraries, it combines ease of use with modern design principles. …
> feat: Add Supercharged Shadcn Components

- README.md
---
name: "feat: Add Solanauth"
about: "Responsive Solana wallet authentication and account modal built on top of @solana/web3.js with NextAuth integration and shadcn/ui"
labels:
- Authentication and account modal
---
Responsive Solana wallet authentication and account modal built on top of @solana/web3.js with NextAuth integration and shadcn/ui
**Important:** The idea of this repository is to …
> Add SolanAuth

- README.md
---
labels:
- feature
---
**What is it?** A dynamic multi-step form. Built with: [ Next.js | shadcn/ui | zustand | framer-motion ]
> Add next-stepper

- README.md
---
name: "feat: Add Extend UI"
about: "Reusable components built on shadcn/ui to increase performance when building web applications."
labels:
- Feature
---
**What is it?** Reusable components built on shadcn/ui to increase performance when building web applications.
> Add Extend UI

- README.md
---
labels:
- feature
---
An open source GraphRAG (Knowledge Graph) built on top of [TiDB Vector](https://www.pingcap.com/ai?utm_source=tidb.ai&utm_medium=community) and [LlamaIndex](https://github.com/run-llama/llama_index) and [DSPy](https://github.com/stanfordnlp/dspy).
Demo site: https://tidb.ai
Boilerplates/Templates …
> feat: add pingcap/autoflow

- README.md
---
name: "feat: add 21st.dev – open source npm for shadcn/ui components"
about: "open source npm for shadcn/ui components. Also: Dribble for design engineers."
labels:
- feature
---
Open source npm for shadcn/ui components. Also: Dribble for design engineers. Install UI components via shadcn CLI, or publish your own.
**What category does it belong to?** 
**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an entirely paid …
> feat: add 21st.dev – open source npm for shadcn/ui components

- README.md
---
name: "shadcn/ui Pricing Page"
about: "Responsive and customizable pricing component built with shadcn/ui"
labels:
- Libs & Component
---
Responsive and customizable pricing component built with shadcn/ui. Features payment frequency toggles, tier highlights and smooth price transition with seamless integration with Next.js applications—perfect for SaaS projects.
**Important:** The idea of this …
> Add shadcn/ui Pricing Page

- README.md
---
name: "feat: Add new excelkits charts tool"
about: "Create shadcn/ui themed charts & graphs"
labels:
- feature
---
Excelkits charts are free zero sign-up tools that allow users to upload their own data and download over a dozen types of charts.  Users have the option to select "Shadcn" to theme the charts according to the Shadcn design standards.
Tools, open to suggestions.
**Important:** The idea of this …
> Update README.md with Excelkits Charts Tool

- README.md
---
name: "feat: Add tweet-to-code"
about: "Collection of designs I have find daily on X/Twitter and transform into fully responsive reusable code examples."
labels:
- feature
---
- Explore a collection of designs I have found on X/Twitter and transformed into fully responsive reusable code examples. Each design is linked to its original creator, and the full project is open source on GitHub. Install directly from our registry using the shadcn/ui cli.
Technologies:
- Shadcn/UI
- Framer Motion
- Lucide Icons
- TypeScript
**What category does it belong to?**
**Please note:** If you are adding a new category, you will need to create a new section in the `README.md` file. Please make sure to update the table of contents as …
> Add tweet-to-code

- README.md
---
name: "feat: Add shaduxe/ui"
about: "Beautifully designed, expertly crafted component variants. The perfect extension for your shadcn/ui components."
labels:
- feature
---
shaduxe/ui is a carefully curated collection of powerful variations built on top of shadcn/ui, designed to take your UI to the next level.
Key Features
Built on shadcn/ui: Leverages the power and flexibility of shadcn/ui components.
Easy Installation: All components are easily installable via the familiar shadcn CLI, but from our custom registry.
Powerful Variations: Extend your design possibilities with expertly crafted component variants. …
> Add shaduxe/ui

- README.md
---
name: "feat: Add shadesigner.com"
labels:
- feature
---
A Shadcn Palette Generator & Theme Designer
Design System
Generate beautiful color palettes for your Shadcn projects. Edit your existing themes. 100% WCAG compliant theme generator.
> Add shadesigner.com

- README.md
---
labels:
- feature
---
PageGen - An AI Page Generator with Claude AI, React and Shadcn UI. Generate web pages from text, screenshot and template with one click.
Tools
**Important:** The idea of this repository is to bring together free projects for open-source contributions. If the proposed addition is an entirely paid …
> Add PageGen AI

- README.md
---
name: "FormFast"
about: "Shadcn Form Builder"
---
Free shadcn form builder with support for building simple and multip-step forms. 
Tools
> Add FormFast

- README.md
---
name: "feat: Add Async Select"
about: "Async select / combobox made with shadcn/ui"
labels:
- component
---
Generic async select component built with shadcn/ui
> Added Async Select to the list

- README.md
---
name: "feat: Add manfromexistence-ui"
about: "Add a new UI library called manfromexistence-ui designed to enhance developer and design experience."
labels:
- feature
---
manfromexistence-ui is a component library aimed at improving the developer and design experience. It provides a comprehensive set of tools, including:
*   **Components:** Reusable UI elements like buttons, forms, modals, etc.
*   **Blocks:** Pre-designed sections or layouts to quickly build pages.
*   **Variants:** Customizable styles and variations of components.
*   **Visualizations:** Charts, graphs, and other data visualization tools.
*   **Icons:** A collection of icons for consistent visual representation.
*   **Fonts:** Curated font choices for typography.
The goal is to provide developers with …
> manfromeixstence-ui added

- README.md
add https://github.com/rbbydotdev/someday
---
labels:
- feature
---
Someday - A Free to host and open-source cal.com / calendly alternative built on Google-Apps-Script for Gmail users.
Tools
- [x ] I have provided a link to the awesome thing.
**Important:** The idea of this repository is to bring together free projects for …
> Add rbbydotdev/someday

- README.md
---
name: Shadcn/Tailwind Full Calendar
about: A full calendar component with a variety of views (days, weeks, months) etc
labels:
- calendar
- schedule
---
It it is a full calendar component which had three views (days, weeks, months). You can also add/manage events with built in dialogs. The calendar is easily customisable and a great alternative to other paid full calendars. 
Libs & Components
Demo: https://calendar-shadcn.vercel.app/
Repo: https://github.com/charlietlamb/calendar
- [*] I checked that it is in alphabetical order.
- [ *] I have checked that the awesome thing is not already listed.
- [ *] I have provided a clear and concise description of the awesome thing.
- [ *] I have provided a link to the awesome thing.
- [ *] I have assigned the correct category to the awesome …
> Add full calendar component to README.md

- README.md
Reverts birobirobiro/awesome-shadcn-ui#187
> Revert "Add full calendar component to README.md"

- README.md
---
labels:
- feature
---
- Tools  
Demo: 
[![AI Shadcn Theme Generator](https://res.cloudinary.com/marcomontalbano/image/upload/v1735449508/video_to_markdown/images/youtube--TBNbLyCZSmE-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://youtu.be/TBNbLyCZSmE?si=ml4H0Q3lQkvTe8mZ "AI Shadcn Theme Generator")
Thank …
> Add tools: ai generator shadcn theme

- README.md
---
name: "feat: Add number scrubber input component"
labels:
- feature
---
A UI component: A draggable numeric input component for React, built with [shadcn/ui](https://ui.shadcn.com/), inspired by desktop video editing software like Resolve.
demo: https://shadcn-react-number-scrubber.vercel.app/
> Add number scrubber input component

- README.md
---
name: "feat: Add shadcn-dropzone"
labels:
- feature
---
File upload/dropzone component I built that tries to implement accessibility like Radix does, uses React Dropzone. Can be installed through the Shadcn cli. [Link to repo](https://www.github.com/janglad/shadcn-dropzone)
**Additional Details (optional)**
> Add shadcn-dropzone

- README.md
---
name: "feat: Add simple-ai.dev"
about: "Adding simple-ai.dev which is a collection of components and blocks for buildding AI apps"
labels:
- feature
---
simple-ai.dev features components and blocks that you can copy into your project to easily build AI applications using the Vercel AI SDK
> Add simple-ai.dev

- README.md
---
name: "feat: Updated actual urls with the link for better readability"
about: "For better readability of the description"
labels:
- feature
---
- Plugins and Extensions  
- Colors and Customizations  
- Animations  
- Tools  
- Websites and Portfolios Inspirations  
- Platforms  
- Ports  
- Design System  
- Boilerplates / Templates  
- 
2. This repository focuses on open-source and freely accessible projects. Paid or fully commercial resources will not be …
> Updated README.md: Updated actual urls with the link for better readability

- README.md
---
labels:
- feature : 
---
Skiper ui Library 
- https://skiper-ui.com/og.png
> Add Skiper UI Library

- README.md
---
name: "docs: Add junwen-k/ui-x"
labels:
- docs
---
A thoughtfully crafted shadcn/ui extension library that mirrors Radix UI conventions, ensuring a consistent, seamless, and intuitive experience—designed to feel like a natural extension of the shadcn ecosystem.
https://ui-x.junwen-k.dev/
Thank you for contributing to …
> docs: add junwen-k/ui-x

- README.md
---
name: "update: fixed github repo link"
about: "Updated 'tremor-raw' to the new 'tremor' github repo"
labels:
- update
---
- N/a
> Update tremor github repo

- README.md
---
name: "feat: add shadcn-drag-and-drop-sort"
about: "Drag and drop to sort and reorder pills of different text widths using dnd-kit"
labels:
- feature
---
**What is it?**  This is a component that allows you to drag and drop to sort and reorder pills of different widths. The widths of the pills are programmatically calculated. It uses NextJS, dnd-kit, TailwindCSS and shadcn/ui. 
**Which section does it belong to?**  Libs and Components  
Thank you for contributing …
> add shadcn-drag-and-drop-sort

- README.md
---
name: "feat: Add linked-chart component"
about: "A recharts based react component integrated with TanStack Data Tables"
labels:
- feature
---
A React component that synchronizes chart and DataTable (shadcn / Tanstack) views, built with shadcn charts / Recharts.
> add linked-chart component

- README.md
---
name: "feat: Add shadcn-cookies"
about: "Sleek and flexible cookie consent component, designed with shadcn/ui"
labels:
---
> Add shadcn-cookies

- README.md
---
name: "feat: windows 11 clone"
about: "website built with shadcn and nextjs"
labels:
- windows 11
- clone
- Portfolio
- Website
---
A sleek Windows 11 clone built with React, Next.js, Tailwind CSS, ShadCN, and Framer-Motion, featuring smooth animations, draggable windows, and a modern design system.
- [Link](https://win11.oimmi.com/)
- [Repo](https://github.com/programming-with-ia/windows-11)
- Websites and Portfolios Inspirations
> add: windows 11 clone

- README.md
---
labels:
- feature
---
commerce-ui library 
site: [ui.stackzero.co](https://ui.stackzero.co/)
> Add commerce-ui Library

- README.md
---
name: "feat: add shadcn-iconpicker"
labels:
- feature
---
**What is it?**  A searchable icon picker component built with NextJS, Lucide-react, TailwindCSS and shadcn/ui. Features infinite scroll, tooltips, and customizable trigger button.
**Which section does it belong to?**  Libs and Components  
https://icon-picker.alan-courtois.fr/
> add shadcn-iconpicker

- README.md
---
labels:
- feature
---
- Plugins and Extensions  
- Colors and Customizations  
- Animations  
- Tools  
- Websites and Portfolios Inspirations  
- Platforms  
- Ports  
- Design System  
- Boilerplates / Templates  
Thank you …
> Fix zoom-chart url

- README.md
---
labels:
- feature
---
- Hundreds of extra block components built for shadcn/ui
- https://www.shadcnblocks.com
> add shadcnblocks.com

- README.md
**Name**: `feat: Add nextjs-multi-image-upload`  
**About**: `Propose adding a new awesome resource related to shadcn/ui`
**Labels**: 
- `feature`
**Description**:
A compact, responsive file uploader I built using `shadcn/ui`, React Hook Form, and Zod. It supports all file types, offers live previews, a glow animation on delete, and uploads to S3/R2 via signed URLs. Fully type-safe and integrates with modern Next.js workflows.
**Link to repo**: [https://github.com/jacksonkasi0/nextjs-multi-image-upload](https://github.com/jacksonkasi0/nextjs-multi-image-upload)
- **Libs and Components**
**Demo & Links**:  
- 🎥 [Loom Demo](https://www.loom.com/share/b7fc9d6650854953b108d17be81c1e2a?sid=627d0c34-27d7-46f5-a258-f278a35a39f8)  
- 📦 [GitHub …
> feat: Add nextjs-multi-image-upload to Libs and Components

- README.md
---
name: "feat: add shadcn-packaged"
labels:
- feature
---
shadcn-packaged: This is an npm package that exports all shadcn/ui components without the need for a CLI, designed for ease of use.
> feat: add shadcn-packaged

- README.md
---
name: "feat: Add tanstack-ui-table"
about: "Propose adding a customizable table component built with @tanstack/table and shadcn/ui"
labels:
- feature
---
A flexible and customizable table component built with @tanstack/table and shadcn/ui. Supports pagination, advanced filtering, column and row reordering (drag-and-drop), dynamic column visibility, and data export (CSV/PDF).
2. This repository focuses on open-source and freely accessible projects. Paid or fully …
> feat: add tanstack-ui-table

- README.md
---
name: "feat: add location picker"
about: "Propose adding a google maps location picker"
labels:
- feature
---
A simple component that lets the user select a point on a map and gives back the latitude and longitude of it. It can be easily dropped on a shadcn form.
> feat: add location picker

- README.md
---
labels:
- feature
---
[DY Comps](https://dycomps.oimmi.com/) — A collection of **shadcn/ui** and **Framer Motion** components for React. Customizable, responsive, and ready to use in any project.
- Live Demo: [https://dycomps.oimmi.com/](https://dycomps.oimmi.com/)  
- Includes a variety of prebuilt components with **Framer Motion** animations.
> add: dycomps

- README.md
---
name: Big Calendar
about: A modern, feature-rich calendar application with multiple viewing options built using Next.js, TypeScript, and Tailwind CSS
labels:
- feature
---
- Demo: https://big-calendar.vercel.app/month-view
- Repo: https://github.com/lramos33/big-calendar
- Screenshots:
> Add big-calendar to README.md

- README.md
---
name: "feat: Add date-time-range-picker-shadcn"
about: "Fully featured date-time range picker with multi-month views, timezone support, preset ranges, and modular components for date and time selection. Built with shadcn/ui."
labels:
- feature
---
Fully featured date-time range picker with multi-month views, timezone support, preset ranges, and modular components for date and time selection. Built with shadcn/ui.
**Additional Details (optional)**
> add date-time-range-picker-shadcn

- README.md
---
name: "rm: dialog-stack link"
about: "dialog-stack link no longer working"
labels:
- clean
---
- Plugins and Extensions  
- Colors and Customizations  
- Animations  
- Tools  
- Websites and Portfolios Inspirations  
- Platforms  
- Ports  
- Design System  
- Boilerplates / Templates  
Thank you for contributing to the …
> rm: dialog-stack link

- README.md
---
name: "feat: Add SHSFUI motion-first UI library"
about: "Propose adding SHSFUI, a motion-first React component library built with Tailwind CSS + Framer Motion. Free and open-source (coming soon)."
labels:
- feature
---
SHSFUI is a motion-first React component library designed with Tailwind CSS and Framer Motion to help build dynamic, high-performance UIs. It's free and open-source (coming soon), making it easily accessible for all developers.
- Animations  
- [Website](https://www.shsfui.com)
- [OG](https://www.shsfui.com/og)
1. If you are introducing a new section, you must also add it to the `README.md` file and update the table of contents …
> feat: add shsfui library

- README.md
---
name: "feat: add tweakcn.com"
about: "Adds tweakcn.com a shadcn theme editor with tailwind v4 integration."
labels:
- feature
---
tweakcn is a powerful theme editor for shadcn/ui components, offering beautifully designed themes and seamless Tailwind V4 CSS integration.
- Colors and Customizations  
- It supports the latest version of shadcn (especially oklch colors)
Thank you for contributing to the …
> add tweakcn.com

- README.md
---
name: "feat: Add simple image uploader"
about: "Propose adding a shadcn image uploader with dnd, validation and previews"
labels:
- feature
---
An image uploader built with [shadcn/ui](https://ui.shadcn.com/), [zod](https://zod.dev/), and [react-dropzone](https://react-dropzone.js.org/) to validate and upload images client side and see a preview of the image you're uploading.
**Which section does it belong to?**
**Additional Details (optional)**
- Demo: https://simple-image-uploader-bice.vercel.app/
- Repository: https://github.com/Cheveniko/simple-image-uploader
**Important Notes:**
1. If you are introducing a new section, you must also add it to the `README.md` file and update the table of contents accordingly.
2. This repository focuses on …
> feat: add simple image uploader

- README.md
---
name: "feat: Add shadcn-builder"
about: "Create beautiful, responsive forms with our easy-to-use form builder and generate React code using shadcn/ui components."
labels:
- forms
- Drag and drop builder
- Code generator
- live preview
---
Website to generate Forms and code using a Drag and Drop editor
- Tools  
> feat: Added Shadcn Builder Tool to the README.md

- README.md
---
labels:
- feature
---
A pair of customizable, animated event timeline components built with [shadcn/ui](https://ui.shadcn.com/), React, and Framer Motion. This package includes two variants:
HorizontalEventTimelineCarousel: A swipeable, card-based carousel for browsing events horizontally.
VerticalEventTimeline: A stacked, expandable timeline with a vertical layout and alternating card positions.
Website: https://roadmap.hncore.website/
> Add Roadmap Timeline Blocks component to the list

- README.md
---
name: "feat: animated tabs"
about: "Vercel-like animated tabs"
labels:
- feature ---
> This is a Vercel-like animated tabs component built using motion
```markdown
| Name | Description | [Link](Your_Link_Here) |
```
> adds animated tabs

- README.md
---
labels:
- feature
---
> BuouUI is a beautifully designed, supa component and template library built on top of shadcn/ui.   It includes production-ready landing pages (like Neuebrutalism), full-stack templates (BuouNext, BuouAI, BuouStore), and a wide range of stunning UI components beyond what's offered in Magic UI.   Dark mode and responsive design are fully supported. Ideal for indie hackers, SaaS builders, and commercial UI projects.
> - Live preview: [BuouUI](https://buouui.com)  
> - Example Landing Page (Neuebrutalism): [Neuebrutalism](https://buouui.com/sections/neuebrutalism)  
> - Offers a suite of templates like …
> adding BuouUI, a component library and template suite for shadcn/ui users

- README.md
---
name: "fix: Update shadcn-builder ref code"
labels:
- fix
---
-
-
```markdown
| Name | Description | [Link](Your_Link_Here) |
```
Thank you …
> fix: Update shadcn-builder ref code

- README.md
---
name: "feat: Adding 8bit cn "
about: "Propose adding a new awesome resource related to shadcn/ui about A set of 8-bit styled components and a code distribution platform. Works with your favorite frameworks. Open Source. Open Code."
labels:
- feature
---
-
-
Just a heads-up: no need to add a date — our system takes care of …
> Adding adding 8bitcn

- README.md
---
name: Shadcn Font Picker
about: An implementation of a Font Picker component, built on top of Shadcn UI's component and Google Fonts API.
labels:
- feature
---
A beautiful and customizable font picker component built with shadcn/ui and Google Fonts API. This component provides an elegant solution for font selection in modern web applications, offering a seamless integration with Google Fonts and a polished UI that matches shadcn's design system.
The component provides a beautiful interface for selecting fonts from Google Fonts, with features like:
- Font preview
- Search functionality
- Category filtering
- Custom styling options
- Responsive design-
1. If you are introducing a new section, you must also add …
> Add shadcn-font-picker to README.md

- README.md
---
name: "feat: add shadboard"
labels:
- feature
---
An admin dashboard template built with Next.js 15, React 19, Tailwind CSS v4, and Shadcn/UI components, featuring starter and full kits for scalable, user-friendly web apps.
- Live demo: [http://shadboard.vercel.app/](http://shadboard.vercel.app/) …
> feat: add shadboard

- README.md
- feature
A highly configurable enterprise-level data table component built on top of shadcn/ui components and TanStack Table (React Table v8). It features server-side pagination, sorting, filtering, row selection, column customization, and data export functionality. Fully integrated with React Query for efficient data fetching and optimistic UI updates.
**Link to repo:** https://github.com/jacksonkasi1/tnks-data-table
**Which section does it belong to?**
**Demo & Links:**
- 🌐 [Live Demo](https://tnks-data-table.vercel.app/)
- 📦 [GitHub Repository](https://github.com/jacksonkasi1/tnks-data-table)
**Key Features:**
- ✅ Server-side pagination, sorting, and filtering
- ✅ Single & multi-row selection with bulk actions
- ✅ Column resizing and visibility …
> feat: Add tnks-data-table to Libs and Components

- README.md
---
name: "feat: Add Shadcn Studio"
labels:
- feature
---
Shadcn studio is an an open-source shadcn registry of copy-and-paste components, blocks, and templates—paired with a powerful theme editor to craft, customize, and ship faster.
shadcn/ui aims to provide core components with a unique distribution system, allowing developers to copy and paste reusable, customizable UI elements directly into their codebase.
While this approach offers flexibility and control, it comes with some limitations: a lack of diverse component variants examples, limited theme customization options, and limited pre-built blocks. Additionally, its extensive customization options, though powerful, can sometimes feel overwhelming, …
> Added Shadcn Studio

- README.md
---
name: "feat: Add omi3/ui to Libs and Components"
labels:
- feature
---
> `@omi3/ui` provides UI components specifically designed for the Omi3 audio processing project. It follows the shadcn/ui philosophy by distributing these components (like an Audio Player block) via its own shadcn/ui-compatible registry, allowing developers to add them directly to their projects using the shadcn CLI.
-
> The components are added using `pnpm shadcn add 'https://omi3.ouestlabs.com/registry/audio-player'` (or similar, depending on the component and package manager). This integrates well with the standard shadcn/ui workflow.
-
1. If you are introducing a new …
> feat: Add omi3/ui to Libs and Components

- README.md
---
name: "feat: Add RetroUI to Libs and Components"
labels:
- feature
---
> A shadcn based component library, inspired by neo brutalism design system.
-
A product demo ↓
https://github.com/user-attachments/assets/e30a1b95-f18a-407d-87f4-f09d08cb8315
- [ x I assigned the correct section to the resource.
Just a heads-up: no need to add a date — our system takes care of that …
> Added Retro UI

- README.md
---
name: "feat: Add Mvpblocks"
labels:
- feature
---
> [**MVPBlocks**](https://blocks.mvp-subha.me) is a fully open-source, developer-first component library built with **Next.js**, **TailwindCSS**, and **shadcn/ui**.  
It helps you launch MVPs faster by offering a curated set of responsive, ready-to-use UI blocks — from dashboards to landing pages. With clean code, CLI support, and instant copy-paste functionality, it’s perfect for building SaaS apps, portfolios, and product prototypes.
> 🔗 GitHub: [https://github.com/subhadeeproy3902/mvpblocks](https://github.com/subhadeeproy3902/mvpblocks)  
> 🧪 Live Demo: [https://blocks.mvp-subha.me](https://blocks.mvp-subha.me) …
> Added Mvpblocks 

- README.md
---
labels:
- feature
---
- HextaUI is open source and completely free!
- It has modern, responsive, and customizable UI components for Next.js.
- Copy, adapt, and personalize them
- Fully customizable with props and Tailwind classes.
- Modern, responsive UI components for Next.js.
- Copy, modify, and integrate with clean code.
- Optimized for performance and responsiveness.
- Seamless support for dark mode.
- Battle-tested components for real-world use.
- [ x ] Libs and Components  
-
**Important Notes:** …
> feat: Add new awesome resource

- README.md
I removed crept studio as the domain has been removed and the repository is archived.
> remove crept-studio

- README.md
---
labels:
- feature
---
> KTUI is a modern, modular JavaScript/TypeScript UI library for building fast, interactive, and beautiful web applications. KTUI offers a comprehensive suite of DOM-based UI components and utilities, designed for flexibility, accessibility, and seamless integration with any web project...
-
-
2. This repository focuses on open-source and freely accessible projects. Paid or fully commercial …
> feat: add ktui

- README.md
---
labels:
- feature
---
- shuip (ship + ui) is a collection of ready-to-use React components designed to accelerate the development of your Next.js applications. The goal is simple: help you ship your projects faster by eliminating the repetitive work of building user interfaces.
- https://shuip.xyz/docs
2. This repository focuses on open-source and …
> feat: add shuip.xyz

- README.md
---
labels:
- feature
---
> Berlix UI is a collection of animated components, built using Tailwind CSS, Motion and Shadcn/ui
-
-
```markdown
| Name | Description | …
```
> feat: add berlix-ui

- README.md
---
name: "feat: Add full stack monorepo starter
about: "Propose adding Full-stack monorepo starter "
labels:
- feature
---
> Full-stack monorepo starter. Built with Fastify, Prisma, better-auth, graphql, graphql-yoga, vitejs, shadcn/ui, docker and much more
-
-
```markdown …
```
> Add Full stack monorepo starter

- README.md
---
labels:
- feature
---
-
-
```markdown
| Name | Description | [Link](Your_Link_Here) |
```
Thank you …
> Updated link for shadcn-examples.

- .github/pull_request_template.md
- .github/workflows/format-readme.yml
- scripts/format-readme.js
- Updated the pull request template for clarity and consistency.
- Introduced a GitHub Actions workflow to automatically format the README.md file.
- Added a script to ensure proper formatting of table entries in README.md.
---
labels:
- feature
---
-
-
2. This repository focuses on open-source and freely accessible projects. Paid or fully commercial …
> Enhance pull request template and add README formatting workflow

- README.md
---
labels:
- feature
---
-
-
Just a heads-up: no need to add a date — our system takes care of that automatically!  
**Also:** Don't worry about formatting — our GitHub Action will automatically format the table and make …
> add: re-ui
